name: "Solidity Version Tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0" # Run at 3:00am UTC every Sunday

jobs:
  solc-version-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Build and test with each supported Solidity version"
        uses: "PaulRBerg/foundry-multibuild@v1"
        with:
          min: "0.8.16"
          max: "0.8.23"
          skip-test: "false"
